const BlogData = [
    {
        id:1,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b1.jpg',
    },
    {
        id:2,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b2.jpg',
    },
    {
        id:3,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b3.jpg',
    },
    {
        id:4,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b4.jpg',
    },
    {
        id:5,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b5.jpg',
    },
    {
        id:6,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b6.jpg',
    },
    {
        id:7,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b7.jpg',
    },
    {
        id:8,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b1.jpg',
    },
    {
        id:9,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b4.jpg',
    },
    {
        id:10,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b5.jpg',
    },
    {
        id:11,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b1.jpg',
    },
    {
        id:12,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b2.jpg',
    },
    {
        id:13,
        title:"the Cotton Jarsey Zip Us Hoodie",
        des:'officia nesciunt harum consectetur ex a, sequi, distinctio, asperiores atque animi expedita maxime autem provident dicta porro totam perferendis voluptatem molestiae blanditiis deserunt.',
        btn:'Continue reading',
        img:'blog/b3.jpg',
    },
]

export default BlogData;